global:
  marketplace-ami: true
  owner: quickstart-eng@amazon.com
  qsname: quickstart-sios-protection-suite
  regions:
    - ap-northeast-2
    - ap-south-1
    - ap-southeast-1
    - ap-southeast-2
    - ca-central-1
    - eu-central-1
    - eu-west-1
      #- sa-east-1
    - us-east-1
    - us-east-2
    - us-west-1
    - us-west-2
  reporting: true
 
tests:
  sios-protection-suite-payg:
    parameter_input: payg.json
    template_file: sios-protection-suite-master.template
  sios-protection-suite-byol:
    parameter_input: byol.json
    template_file: sios-protection-suite-master.template
